# Generated by Django 4.2.29 on 2026-03-06 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='estoque_atual',
            field=models.PositiveIntegerField(default=0, verbose_name='Estoque Atual'),
        ),
        migrations.AddField(
            model_name='produto',
            name='ncm',
            field=models.CharField(blank=True, max_length=10, verbose_name='NCM'),
        ),
    ]
