# Generated by Django 4.2.29 on 2026-03-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_produto_estoque_atual_produto_ncm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='codigo',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Descrição'),
        ),
    ]
