# Generated by Django 4.2.29 on 2026-03-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_alter_produto_codigo_alter_produto_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='ncm',
            field=models.CharField(blank=True, db_index=True, max_length=10, verbose_name='NCM'),
        ),
    ]
