# Generated by Django 4.2.29 on 2026-03-07 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_alter_produto_ncm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='ncm',
            field=models.CharField(blank=True, max_length=10, verbose_name='NCM'),
        ),
    ]
