# Generated by Django 4.2.29 on 2026-03-06 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name': 'Perfil de Usuário', 'verbose_name_plural': 'Perfis de Usuários'},
        ),
        migrations.AddField(
            model_name='perfil',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='cargo',
            field=models.CharField(choices=[('VENDEDOR', 'Vendedor'), ('ORCAMENTISTA', 'Orçamentista'), ('GERENTE', 'Gerente'), ('ADMIN', 'Administrador')], default='VENDEDOR', max_length=50),
        ),
    ]
