# Generated by Django 4.2.29 on 2026-03-05 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusOportunidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Status')),
                ('cor', models.CharField(default='#3498db', help_text='Cor em Hexadecimal', max_length=7)),
                ('ordem', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=1, verbose_name='Ordem no Kanban')),
                ('notifica_setor_tecnico', models.BooleanField(default=False, verbose_name='Notifica setor técnico?')),
            ],
            options={
                'verbose_name': 'Status de Oportunidade',
                'verbose_name_plural': 'Status de Oportunidades',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Oportunidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Excluído?')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Exclusão')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('numero', models.PositiveIntegerField(editable=False, unique=True, verbose_name='Nº Oportunidade')),
                ('titulo', models.CharField(max_length=300, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('valor_estimado', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Valor Estimado')),
                ('margem_lucro', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Margem de Lucro (%)')),
                ('probabilidade', models.PositiveIntegerField(default=50, help_text='0-100%', verbose_name='Probabilidade (%)')),
                ('data_prevista_fechamento', models.DateField(blank=True, null=True, verbose_name='Previsão de Fechamento')),
                ('fonte', models.CharField(choices=[('INDICACAO', 'Indicação'), ('SITE', 'Site'), ('PROSPECCAO', 'Prospecção'), ('WHATSAPP', 'WhatsApp'), ('OUTRO', 'Outro')], default='SITE', max_length=20, verbose_name='Fonte')),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta')], default='MEDIA', max_length=10, verbose_name='Prioridade')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oportunidades', to='clientes.cliente', verbose_name='Cliente')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oportunidades', to='comercial.statusoportunidade', verbose_name='Status')),
                ('vendedor', models.ForeignKey(blank=True, help_text='Vendedor responsável pelo registro.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_vendedor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Oportunidade',
                'verbose_name_plural': 'Oportunidades',
                'ordering': ['-numero'],
            },
        ),
    ]
