# Generated by Django 4.2.29 on 2026-03-06 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comercial', '0002_alter_oportunidade_vendedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveSmallIntegerField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')], verbose_name='Mês')),
                ('ano', models.PositiveIntegerField(default=2026, verbose_name='Ano')),
                ('valor_meta', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor da Meta (R$)')),
                ('vendedor', models.ForeignKey(blank=True, help_text='Deixe em branco para meta GLOBAL da empresa.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meta Mensal',
                'verbose_name_plural': 'Metas Mensais',
                'ordering': ['-ano', '-mes'],
                'unique_together': {('mes', 'ano', 'vendedor')},
            },
        ),
    ]
