# Generated by Django 4.2.29 on 2026-03-07 05:38

import comercial.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comercial', '0003_metamensal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoOportunidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=comercial.models.upload_path_oportunidade)),
                ('nome_original', models.CharField(max_length=255)),
                ('caminho_relativo', models.CharField(default='', help_text='Preserva a estrutura de pastas original', max_length=500)),
                ('extensao', models.CharField(blank=True, max_length=15)),
                ('tamanho', models.BigIntegerField(default=0, help_text='Tamanho em bytes')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('oportunidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='comercial.oportunidade')),
            ],
            options={
                'verbose_name': 'Arquivo da Oportunidade',
                'verbose_name_plural': 'Arquivos da Oportunidade',
                'ordering': ['caminho_relativo', 'nome_original'],
            },
        ),
    ]
