# Generated by Django 4.2.29 on 2026-03-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0004_arquivooportunidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunidade',
            name='detalhes_perda',
            field=models.TextField(blank=True, null=True, verbose_name='Detalhes da Perda'),
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='motivo_perda',
            field=models.CharField(blank=True, choices=[('PRECO', 'Preço Elevado'), ('PRAZO', 'Prazo de Entrega'), ('TECNICO', 'Especificação Técnica'), ('CONCORRENCIA', 'Perdeu para Concorrência'), ('CANCELADO', 'Projeto Cancelado pelo Cliente'), ('OUTRO', 'Outro Motivo')], max_length=20, null=True, verbose_name='Motivo da Perda'),
        ),
    ]
