# Generated by Django 4.2.29 on 2026-03-09 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0005_oportunidade_detalhes_perda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunidade',
            name='liberado_orcamento',
            field=models.BooleanField(default=False, help_text='Se marcado, a proposta pode ser gerada e a OP não pode voltar no Kanban.', verbose_name='Liberado pelo Orçamento'),
        ),
    ]
