# Generated by Django 4.2.29 on 2026-03-06 02:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0002_cliente_cpf_alter_cliente_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor'),
        ),
    ]
