# Generated by Django 4.2.29 on 2026-03-05 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoPreco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Padrão', max_length=100, verbose_name='Nome da Configuração')),
                ('markup_engenharia', models.DecimalField(decimal_places=4, default=0.1, max_digits=5, verbose_name='Engenharia (%)')),
                ('markup_capitalizacao', models.DecimalField(decimal_places=4, default=0.05, max_digits=5, verbose_name='Capitalização (%)')),
                ('markup_frete', models.DecimalField(decimal_places=4, default=0.03, max_digits=5, verbose_name='Frete (%)')),
                ('markup_imposto', models.DecimalField(decimal_places=4, default=0.15, max_digits=5, verbose_name='Impostos (%)')),
                ('markup_comissao', models.DecimalField(decimal_places=4, default=0.05, max_digits=5, verbose_name='Comissão (%)')),
                ('markup_difal', models.DecimalField(decimal_places=4, default=0.0, max_digits=5, verbose_name='DIFAL (%)')),
                ('markup_frete_especial', models.DecimalField(decimal_places=4, default=0.0, max_digits=5, verbose_name='Frete Especial (%)')),
                ('margem_contribuicao_padrao', models.DecimalField(decimal_places=4, default=0.2, max_digits=5, verbose_name='Margem Contribuição Padrão (%)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
            ],
            options={
                'verbose_name': 'Configuração de Preço',
                'verbose_name_plural': 'Configurações de Preço',
            },
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Excluído?')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Exclusão')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('numero', models.PositiveIntegerField(editable=False, verbose_name='Nº Orçamento')),
                ('revisao', models.PositiveIntegerField(default=0, verbose_name='Revisão')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('ELABORACAO', 'Em Elaboração'), ('REVISAO', 'Aguardando Revisão'), ('ENVIADO', 'Enviado ao Cliente'), ('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado'), ('CANCELADO', 'Cancelado')], default='RASCUNHO', max_length=20, verbose_name='Status')),
                ('custo_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Custo Total')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Valor Total Venda')),
                ('margem_contrib', models.DecimalField(decimal_places=4, default=0.2, max_digits=5, verbose_name='Margem de Contribuição (%)')),
                ('desconto_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Desconto Final (%)')),
                ('validade_dias', models.PositiveIntegerField(default=15, verbose_name='Validade (Dias)')),
                ('prazo_entrega', models.CharField(blank=True, max_length=100, verbose_name='Prazo de Entrega')),
                ('condicao_pagamento', models.CharField(blank=True, max_length=255, verbose_name='Condição de Pagamento')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos', to='clientes.cliente', verbose_name='Cliente')),
                ('resp_orcam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamentos_tecnicos', to=settings.AUTH_USER_MODEL, verbose_name='Orçamentista')),
                ('vendedor', models.ForeignKey(blank=True, help_text='Vendedor responsável pelo registro.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_vendedor', to=settings.AUTH_USER_MODEL)),
                ('versao_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisoes', to='orcamentos.orcamento', verbose_name='Versão Original')),
            ],
            options={
                'verbose_name': 'Orçamento',
                'verbose_name_plural': 'Orçamentos',
                'ordering': ['-numero', '-revisao'],
                'unique_together': {('numero', 'revisao')},
            },
        ),
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Kit')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição/Finalidade')),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kits', to='orcamentos.orcamento', verbose_name='Orçamento')),
            ],
            options={
                'verbose_name': 'Kit',
                'verbose_name_plural': 'Kits',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='ItemOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, verbose_name='Código (Snapshot)')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição (Snapshot)')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantidade')),
                ('custo_unit_snapshot', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Custo Unitário (Snapshot)')),
                ('vlr_unit_venda', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Unitário Venda')),
                ('desconto_unit_valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Desconto Unitário (Valor)')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='orcamentos.kit', verbose_name='Kit')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos_relacionados', to='produtos.produto', verbose_name='Produto Original')),
            ],
            options={
                'verbose_name': 'Item de Orçamento',
                'verbose_name_plural': 'Itens de Orçamento',
            },
        ),
    ]
