# Generated by Django 4.2.29 on 2026-03-05 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0002_alter_itemorcamento_vlr_unit_venda'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorcamento',
            name='desconto_percent_item',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Desconto Item (%)'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='aprovado_gerencia',
            field=models.BooleanField(default=False, verbose_name='Aprovado pela Gerência?'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='motivo_rejeicao',
            field=models.TextField(blank=True, verbose_name='Motivo Rejeição'),
        ),
    ]
