# Generated by Django 4.2.29 on 2026-03-06 02:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orcamentos', '0003_itemorcamento_desconto_percent_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamentos_comerciais', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor'),
        ),
    ]
