# Generated by Django 4.2.29 on 2026-03-06 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0002_alter_oportunidade_vendedor'),
        ('orcamentos', '0004_alter_orcamento_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='oportunidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamentos', to='comercial.oportunidade', verbose_name='Oportunidade (CRM)'),
        ),
    ]
