# Generated by Django 4.2.29 on 2026-03-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0005_orcamento_oportunidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('ELABORACAO', 'Em Elaboração'), ('REVISAO', 'Aguardando Revisão'), ('ENVIADO', 'Enviado ao Cliente'), ('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado'), ('CANCELADO', 'Cancelado')], db_index=True, default='RASCUNHO', max_length=20, verbose_name='Status'),
        ),
    ]
