# Generated by Django 4.2.29 on 2026-03-06 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_remove_cliente_endereco_cliente_bairro_cliente_cep_and_more'),
        ('comercial', '0003_metamensal'),
        ('produtos', '0003_alter_produto_codigo_alter_produto_descricao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orcamentos', '0006_alter_orcamento_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaopreco',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='configuracaopreco',
            name='margem_contribuicao_padrao',
            field=models.DecimalField(decimal_places=4, default=0.2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='configuracaopreco',
            name='markup_capitalizacao',
            field=models.DecimalField(decimal_places=4, default=0.05, max_digits=5),
        ),
        migrations.AlterField(
            model_name='configuracaopreco',
            name='markup_comissao',
            field=models.DecimalField(decimal_places=4, default=0.05, max_digits=5),
        ),
        migrations.AlterField(
            model_name='configuracaopreco',
            name='markup_difal',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='configuracaopreco',
            name='markup_engenharia',
            field=models.DecimalField(decimal_places=4, default=0.1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='configuracaopreco',
            name='markup_frete',
            field=models.DecimalField(decimal_places=4, default=0.03, max_digits=5),
        ),
        migrations.AlterField(
            model_name='configuracaopreco',
            name='markup_frete_especial',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='configuracaopreco',
            name='markup_imposto',
            field=models.DecimalField(decimal_places=4, default=0.15, max_digits=5),
        ),
        migrations.AlterField(
            model_name='itemorcamento',
            name='codigo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='itemorcamento',
            name='custo_unit_snapshot',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='itemorcamento',
            name='desconto_percent_item',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='itemorcamento',
            name='desconto_unit_valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='itemorcamento',
            name='descricao',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='itemorcamento',
            name='kit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='orcamentos.kit'),
        ),
        migrations.AlterField(
            model_name='itemorcamento',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_orcamento', to='produtos.produto'),
        ),
        migrations.AlterField(
            model_name='itemorcamento',
            name='quantidade',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name='itemorcamento',
            name='vlr_unit_venda',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kit',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='kit',
            name='nome',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='kit',
            name='orcamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kits', to='orcamentos.orcamento'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='aprovado_gerencia',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos', to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='condicao_pagamento',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='custo_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='desconto_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='margem_contrib',
            field=models.DecimalField(decimal_places=4, default=0.2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='motivo_rejeicao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='numero',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='oportunidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamentos', to='comercial.oportunidade'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='prazo_entrega',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='resp_orcam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamentos_tecnicos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='revisao',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('ELABORACAO', 'Em Elaboração'), ('REVISAO', 'Aguardando Revisão'), ('ENVIADO', 'Enviado ao Cliente'), ('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado'), ('CANCELADO', 'Cancelado')], default='RASCUNHO', max_length=20),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='validade_dias',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamentos_comerciais', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='versao_pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisoes', to='orcamentos.orcamento'),
        ),
    ]
