# Generated by Django 4.2.29 on 2026-03-07 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0007_alter_configuracaopreco_ativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='prioridade',
            field=models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta')], default='MEDIA', max_length=10),
        ),
    ]
