# Generated by Django 4.2.29 on 2026-03-07 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0008_orcamento_prioridade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamento',
            name='prioridade',
        ),
    ]
